name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: financementor
  TAG: latest
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
          path: |
            /var/lib/docker/image
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
    - name: Build the Docker image
      run: docker build . --file ./FinanceMentor/Server/Dockerfile --tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: docker login --username $DOCKERHUB_USERNAME --password-stdin <<< $DOCKERHUB_TOKEN

      - name: Push Docker image to Docker Hub (latest)
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG
