name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  IMAGE_NAME: financementor
  TAG: latest
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: Builder
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        id: Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('./FinanceMentor/Server/Dockerfile') }}
          restore-keys: ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        id: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: Build_Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./FinanceMentor/Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FinanceMentor'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0907a679138463cb4153f4bf3738aee }}
        images: 'index.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}'
